### PR TITLE
Reflect license and repo in package.json

### PR DESCRIPTION
**Pull request by srvance**
Makes it easier for automated scanners to recognize.

### CODE REVIEW

**Comment by jonny-improbable** [comment]
Bump; the current setup of this package confuses https://github.com/davglass/license-checker/ which fouls up our CI

**Comment by srvance** [comment]
@jonny-improbable I'm not sure I understand the comment. Bump? The proposed additions foul up your CI? How can I know this? What's the path forward?

**Comment by jonny-improbable** [comment]
Hey @srvance, sorry, [this](https://www.webopedia.com/TERM/T/thread_bump.html) is what I meant by "bump" :)

Your PR solves my CI problem; I would like the maintainer(s) of this package to merge it 😁

**Comment by srvance** [comment]
Thanks for the explanation. I've been waiting for this, as well.

@ssoper @stevenmiller888 @stephenmathieson @f2prateek Can we merge this?

**Comment by f2prateek** [comment]
thanks!

**Comment by srvance** [comment]
Thank you, @f2prateek !

**Comment by brianoctan** [comment]
Thank you for this.

Would it be possible to push these changes [over to npm?](https://www.npmjs.com/package/@segment/loosely-validate-event) It might require a minor version bump to reflect it on the npm registry.

**Pull request merged**
